### ISSUE TITLE
Selecting a cartridge dir on SD leads to error messages

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#186]
A user claimed on support, that WhereYouGo always shows "Invalid cartridge" (Ungültige Cartridge) once he either starts the app or selects a cartridge. He selected a storage directory on SD card. After changing this to the internal memory the problem was gone.

**Version of WhereYouGo used:**
2020.04.07

**System information (Android version, device model):**
Android 10, Samsung S10 plus

**Is the problem reproducible:**
To be investigated

**Comment by bekuno** [comment]
I could reproduce it on an android 9 device.

**Comment by Lineflyer** [comment]
I assume it is because we would need to have write access but there is no chance on SD.

IMHO we could completely remove the ability to choose a random dir and just use a default location working on all devices. This would also make it easier to write a valid beginners guide.

**Comment by SchoolGuy** [comment]
@Lineflyer I would not like that. I think it is pretty convenient for a user to choose whatever directory he likes. I think we can document very well how to choose a directory, personally I have explained that to various people already. Thus I think documenting that the SD-Card is not an option is the better choice in my eyes, even if that means that some users may not understand that because they don't read the documentation.

**Comment by Lineflyer** [comment]
We should at least provide a proper error message if the user tries to select a non writeable location.

**Comment by ajcampos** [comment]
I don't have an SD card but it doesn't accept a personalised directory. It worked before.

**Comment by ajcampos** [comment]
Understood. Many thanks.

A quinta, 10/02/2022, 21:44, Lineflyer ***@***.***> escreveu:
