### ISSUE TITLE
switch to targetSdkVersion 30 or above

### ISSUE THREAD

**Issue by bekuno** [cgeo/WhereYouGo#274]
>     * Do we meet this requirement for the planned branches/releases?

The release has `targetSdkVersion 28`, master has `29`.
I will check if we need aditional changes for release.
If we can not change the targetSdk for release then I suggest to not create a legacy release on the Play Store.

_Originally posted by @bekuno in https://github.com/cgeo/WhereYouGo/issues/266#issuecomment-770431260_

**Comment by Lineflyer** [comment]
Meanwhile we need targetSDKversion 30 or above.

**Comment by fm-sys** [comment]
If we have the necessary resources, we should probably directly switch to SDK31 so that we some more time until the whole story starts again...

**Comment by Lineflyer** [comment]
I will start with creating a project listing the known "Must have" fixes/changes at least.

**Comment by Lineflyer** [comment]
A quick compile and emulator check showed, that 
- With targetSDK30 the app compiles and seems to run basically (not tested any deeper)
- With targetSDK31 it does not compile (needs to be analyzed)

Therefore (assuming there are not any major development resources right now) I suggest to test targetSDK=30 on `master` in nightlies to see if any follow-up changes are needed.
Targeting SDK30 would at least for now enable us to push updates to Google Play, which are needed due to Android 12 problems. 
Therefore I propose to go the SDK=30 way if no regressions show up, unless someone wants to dive into targetSDK=31 on short term.
