### ISSUE TITLE
Openstreetmaps.org download error

### ISSUE THREAD

**Issue by AutumnSpark1226** [cgeo/WhereYouGo#297]
## Bug description

The app can't download map tiles from openstreetmaps.org

### Steps to reproduce the problem

Internet connection works fine
1. open app
2. go to map
3. map source > OSM Mapnik (online)

### Actual result after these steps

I only see the background of the activity and no map tiles.  
After debugging I found this:
E/TileDownloader: null
    java.io.FileNotFoundException: https://a.tile.openstreetmap.org/12/655/1581.png
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
        at org.mapsforge.android.maps.mapgenerator.tiledownloader.TileDownloader.executeJob(TileDownloader.java:65)
        at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:97)
        at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:141)

### Expected result after these steps

I expected to see a map.

## WhereYouGo version

2020.08.21

## Reproducible

Yes

## System information

Manufacturer: Samsung / Android emulator
Model: SM-J330F / Android studio AVD
Android version: 9 (API level 28) / 11.0 (API level 30)

**Comment by bekuno** [comment]
Problem is reprodicible.

Very strange, as the link in the exception works.
Maybe a server side configuration/check.

**Comment by SammysHP** [comment]
Can someone log the HTTP request header (and response header) please? There are several preconditions that are checked by OSM servers.

**Comment by hakuchi** [comment]
@SammysHP @bekuno 
what if we change OSM Mapnik to https://tile.osm.ch/switzerland/{z}/{x}/{y}.png
looks similar to openstreetmap.org tiles, but with contour lines and hillshade.

Other question is if we can use OSM.ch tiles in WhereYouGo

**Comment by SchoolGuy** [comment]
@hakuchi Do you know what resources are needed to host your own tiles etc? Depending on the resources I would think about sponsoring the infrastructure...

**Comment by hakuchi** [comment]
@SchoolGuy sry no

**Comment by SammysHP** [comment]
@hakuchi Not a good idea. There's a high risk that we cause too much traffic for their server. Well, not with WhereYouGo probably.

If we respect the tile usage policy, there's no free solution for our use case. There are plans for about 450 €/month.

For hosting our own tile server I'd say a good start would be 4 TB SSD (raid 1, so 8 TB total minimum), 48-64 GB RAM and a pretty good 10+ core CPU. Don't forget we have to render the whole world.

**Comment by SchoolGuy** [comment]
@SammysHP Okay let me check some things at work tomorrow...

**Comment by Lineflyer** [comment]
I think we only need to know the details like `useragent` WhereYouGo uses.
As I am not familiar with the code I tried to find it out with Android Studio profiler but failed.

Someone with an idea about the code should look this up. We should IMHO use a very informative useragent. not just some random or defaulted, so that the openstreetmap guys know who is calling.

**Comment by SammysHP** [comment]
That's why I asked for the headers. The useragent is not the only information that is checked.

**Comment by SchoolGuy** [comment]
@SammysHP This is not a problem since I am having my own rack at home and that is fully automated via Salt, MicrosOS and k3s. Space for new hardware is also there. The only thing I worry about is the bandwidth. With the 50 MBits upload at home I can't do much for such a service. The download I can easily manage with 800 Mbits dedicated for the service (we have 1 Gbits).

The hardware for hosting I could get possibly at work but I guess there I can't get a permit for that amount of bandwidth, after all we do have our own things to run there. I also thought about Co Location but I decided against that for my private Usecase because it is basically not affordable as a private person, although I would be in near reach of the Nürnberg Hetzner Colocation location. Also I thought about the public cloud but that is the most pricy option afaik.

But let's see what strings I can pull at work.

**Comment by SchoolGuy** [comment]
So I found this: https://switch2osm.org/serving-tiles/

These requirements I can get easily even without buying new hardware. But the problem with the bandwidth stays. I get 5G at home, so I could get a Telekom Unlimited contract which has up to 100 MBits Upload with 5G but I doubt that this is actually reached and I doubt that I can get a static or dynamic IP for a mobile phone contract.

Fiber is sadly not available at home and there is no plans that some provider changes that in the foreseeable future...

**Comment by SchoolGuy** [comment]
Okay so basically Hetzner is the only option in the end: https://help.openstreetmap.org/questions/64405/tile-server-hardware-requirements

As said, I have the hardware but not the bandwidth at home or work. And in the next year or so I can't afford to sponsor 80€ a month. So as much as I would love the help, it seems I need to stick to maintaining code. :(

**Comment by Lineflyer** [comment]
From reading Google and briefly looking at the code I would say, that WhereYouGo does not explicitly define an own user agent but just using the underlying generic okhttp user agent.

But I am not 100% sure as I have only very limited knowledge of network traffic handling in Android/Java.
