### ISSUE TITLE
new icon?

### ISSUE THREAD

**Issue by ztNFny** [cgeo/WhereYouGo#300]
As you might know I'm working on new map icons for c:geo (https://github.com/cgeo/cgeo/issues/11139) and that of course includes type icons. While at it it'd maybe make sense to also refresh the WYG icon.

The current drafts for WIG-type-icon:
![image](https://user-images.githubusercontent.com/1258173/127740416-0fb70690-6705-46d8-824d-ac9b17a5a6f7.png)

The bee one is quite close to the current WYG icon, the others are more similar to the official icon.

Please let me know whether there's interest in this.

**Comment by SchoolGuy** [comment]
I personally would have interest in that and would vote for the thrid/middle icon. But I believe in any case that this is a big step forward!

**Comment by Lineflyer** [comment]
I do like the second of third one. In any case we should perhaps use the icon we decided for in cgeo also as app icon for WhereYouGo.

**Comment by ztNFny** [comment]
The third one doesn't work, it's too busy with 3 elements (ring + circle + triangle)

This is the approach I'm currently taking:
![image](https://user-images.githubusercontent.com/1258173/128517040-9b450b26-a470-45b4-b3ab-4b7d7625a5f8.png)

**Comment by ztNFny** [comment]
latest draft (from c:geo project)
![wig](https://user-images.githubusercontent.com/1258173/131545139-b379b5aa-5fd7-488f-b3fe-b06456a059d5.png)

**Comment by SchoolGuy** [comment]
I love it. I would vote for integrating it!

**Comment by ztNFny** [comment]
With the c:geo icons pretty much finalized I took a stab at the WYG app-icon again. Added some finetuning and drop-shadow.
![image](https://user-images.githubusercontent.com/1258173/140386456-5d2a54f9-b292-451e-b1d4-dfdb7026d126.png)

**Comment by Lineflyer** [comment]
Thanks for working on this.
I don't want to block further work on this, but:

Currently we could not introduce it as the current code status does not fulfill the Google requirements since a while (permission on runtime, targetSDK, etc.).
The fact, that we have more or less no contributors brings us somehow back to the topic once addressed by @eddiemuc a while ago 
What to do next with WhereYouGo? 
- Include it into c:geo to use synergies and get it back releasable again?
- Change WhereYouGo in a way that major parts of c:geo (e.g. map) can be reused but remains an own app?

I don't want to misuse this issue, not sure if we have the discussion here somewhere or whether it was in our monthly call only.

**Comment by ztNFny** [comment]
> What to do next with WhereYouGo?

I suggest to start a discussion for that (unless there's one in cgeo already?)

A new icon shouldn't be the only change for a release anyway 😆 It's ready now and can be pulled whenever.
