### ISSUE TITLE
Beta users have file access problems on API30+

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/WhereYouGo#351]
Users reported, that they can't see any file (e.g. map files or cartridges) unless they have been downloaded by WhereYouGo.

I stumbled upon this line in AndroidManifest.xml:
https://github.com/cgeo/WhereYouGo/blob/35b4fe547a464d42a095f9fcb8abbd19fadc7792/src/main/AndroidManifest.xml#L36

I think we need to use `android:preserveLegacyExternalStorage="true"` instead to keep the loophole open, like we do in c:geo:
https://github.com/cgeo/cgeo/blob/24dd6766b0c713cffed3ade8feb66b4a755bd270/main/AndroidManifest.xml#L56

@eddiemuc 
Do you remember the difference between both?

**Comment by eddiemuc** [comment]
android:preserveLegacyExternalStorage="true" is meant for data model upgrade only. It will preserve legacy access only if an app upgrades from Android SDK < 30 to SDK>= 30, and it will do so just this one time. It will not allow legacy access on new installations or after upgrading an app from a previous version using SDK >=30

Actually I think we can remove it in c:geo now too since all c:geo installations < SDK30 should be replaced by a cgeo version with >=SDK30 by now. But the settings doesn't harm either.

**Comment by Lineflyer** [comment]
@eddiemuc 

Ok, but for WhereYouGo this probably means we should use the preserve key as we target API30.

**Comment by eddiemuc** [comment]
> @eddiemuc
> 
> Ok, but for WhereYouGo this probably means we should use the preserve key as we target API30.

As you wrote correctly in your PR: this will help ONE TIME those users UPGRADING from previous WhereYouGo to the current one. 

But be careful: once a SDK30/preserve-flag-version is out, we can't set the preserve-flag ever again for a next release. This means: once such a version is out, we can never ever do data migration on existing WhereYouGo app installation again. 

The preserve-flag is strictly meant for a one-time data migration. Its misuse to help out users in the short term will bite us in the back in the long term. This one-time restriction is the reason why I wanted to have SAF implementation out once with SDK29 still enabled - so we could be sure the migration is bug-free before we enable the one-time-shot SDK30/preserve=true. We will not have such a migration shot when we set SDK30/preserve=true without actually performing any data migration
